In [1]:
import numpy as np
from scipy.linalg import eig, inv, det

In [2]:
def matrix_properties(matrix):
    properties = {}
    properties['Determinant'] = det(matrix)
    properties['Trace'] = np.trace(matrix)
    properties['Rank'] = np.linalg.matrix_rank(matrix)
    properties['Is Symmetric'] = np.allclose(matrix, matrix.T)
    
    try:
        properties['Inverse'] = inv(matrix)
    except np.linalg.LinAlgError:
        properties['Inverse'] = "Non-invertible matrix"

    eigenvalues, eigenvectors = eig(matrix)
    properties['Eigenvalues'] = eigenvalues
    properties['Eigenvectors'] = eigenvectors
    
    return properties

# Example matrix
matrix = np.array([
    [4, 0, 2],
    [0, 3, 0],
    [2, 0, 4]
])

# Get matrix properties
props = matrix_properties(matrix)

# Print the properties
for prop, value in props.items():
    print(f"{prop}:")
    print(value, "\n")

Determinant:
36.0 

Trace:
11 

Rank:
3 

Is Symmetric:
True 

Inverse:
[[ 0.33333333  0.         -0.16666667]
 [ 0.          0.33333333 -0.        ]
 [-0.16666667  0.          0.33333333]] 

Eigenvalues:
[6.+0.j 2.+0.j 3.+0.j] 

Eigenvectors:
[[ 0.70710678 -0.70710678  0.        ]
 [ 0.          0.          1.        ]
 [ 0.70710678  0.70710678  0.        ]] 



##### Explanation:
- Determinant and Trace: Basic properties calculated directly from the matrix.
- Inverse: Computed if the matrix is non-singular (determinant is not zero).
- Eigenvalues and Eigenvectors: Obtained using the eig function, which returns both.
- Rank: The number of linearly independent rows or columns.
- Symmetry Check: Determines if the matrix is symmetric by checking if it equals its transpose.

In [3]:
import numpy as np
from numpy.linalg import eig, det, matrix_power, norm
from scipy.linalg import eigh

([[-1, 3/2]])
([[1, 1]])

([[-1, 3/2]])
([[2/3, 1]])

In [4]:
# Question 1: Matrix properties
matrices = [
    np.array([[-1, 3/2], [1, -1]]),
    np.array([[-1, 3/2], [2/3, -1]]),
    np.eye(3)  # Identity matrix 3x3
]

# Show properties of matrices
for i, matrix in enumerate(matrices):
    print(f"Matrix {i+1} determinant: {det(matrix)}")
    print(f"Matrix {i+1} eigenvalues: {eig(matrix)[0]}")
    print()

Matrix 1 determinant: -0.5
Matrix 1 eigenvalues: [ 0.22474487 -2.22474487]

Matrix 2 determinant: 0.0
Matrix 2 eigenvalues: [-1.11022302e-16 -2.00000000e+00]

Matrix 3 determinant: 1.0
Matrix 3 eigenvalues: [1. 1. 1.]



- first of all the matrix multiplication doesn't work becaue the dimentions of the identity matrix don't match the previous matrices.

In [5]:
# Question 2: Show that A^n = XΛ^nX^-1
A = np.array([[1, 1], [1, 0]])
eigenvalues, eigenvectors = eig(A)
Lambda = np.diag(eigenvalues)
n = 5  # Example power
A_n = matrix_power(A, n)
X = eigenvectors
X_inv = np.linalg.inv(X)
A_n_formulated = X @ matrix_power(Lambda, n) @ X_inv
print(f"A^n calculated: \n{A_n}")
print(f"A^n using formula: \n{A_n_formulated}")

A^n calculated: 
[[8 5]
 [5 3]]
A^n using formula: 
[[8. 5.]
 [5. 3.]]
